version: "3.8"

services:
  db:
    image: mysql:5.8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: Haineux_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      db_host: db
      db_user: user
      db_password: password

volumes:
  db_data:



